// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/falcosecurity/cloud-native-security-hub/pkg/resource (interfaces: Updater)

// Package mock_resource is a generated GoMock package.
package mock_resource

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockUpdater is a mock of Updater interface
type MockUpdater struct {
	ctrl     *gomock.Controller
	recorder *MockUpdaterMockRecorder
}

// MockUpdaterMockRecorder is the mock recorder for MockUpdater
type MockUpdaterMockRecorder struct {
	mock *MockUpdater
}

// NewMockUpdater creates a new mock instance
func NewMockUpdater(ctrl *gomock.Controller) *MockUpdater {
	mock := &MockUpdater{ctrl: ctrl}
	mock.recorder = &MockUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockUpdater) EXPECT() *MockUpdaterMockRecorder {
	return m.recorder
}

// IncrementDownloadCountFor mocks base method
func (m *MockUpdater) IncrementDownloadCountFor(arg0 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementDownloadCountFor", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// IncrementDownloadCountFor indicates an expected call of IncrementDownloadCountFor
func (mr *MockUpdaterMockRecorder) IncrementDownloadCountFor(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementDownloadCountFor", reflect.TypeOf((*MockUpdater)(nil).IncrementDownloadCountFor), arg0)
}
